Build.BRAND=samsung
Build.DEVICE=e1q
Build.MODEL=SM-S921U
Build.MANUFACTURER=samsung
Build.PRODUCT=e1q
Build.HARDWARE=s5e9945
Build.ID=UP1A.231005.007
Build.FINGERPRINT=samsung/e1q/e1q:14/UP1A.231005.007/S921USQU1AXB7:user/release-keys
Build.VERSION.SDK_INT=34
Build.VERSION.RELEASE=14
Screen.Density=450
Screen.Width=1080
Screen.Height=2340
Vending.versionString=41.3.22-29 [0] [PR] 640887647
Vending.version=84132210
Build.RADIO=g5300n-230203-230323-B-9801058,g5300n-230203-230323-B-9801058
Build.BOOTLOADER=e1q-1.0-9716681
Client=android-google
GSF.version=203615037
CellOperator=310
SimOperator=310
Roaming=mobile-notroaming
TimeZone=UTC-10
TouchScreen=3
Keyboard=1
Navigation=1
ScreenLayout=2
HasHardKeyboard=false
HasFiveWayNavigation=false
LowRamDevice=false
MaxNumOfCPUCores=8
TotalMemoryBytes=8354971648
GL.Version=196608
GL.Extensions=GL_OES_egl_image_external,GL_OES_texture_npot,GL_KHR_texture_compression_astc_ldr
SharedLibraries=android.test.base,com.google.android.gms,android.ext.shared
Features=android.hardware.location,android.hardware.wifi,android.hardware.bluetooth,android.hardware.touchscreen,android.hardware.camera,android.hardware.sensor.accelerometer,android.hardware.sensor.gyroscope,android.hardware.telephony,android.hardware.nfc,android.hardware.fingerprint,android.hardware.microphone,android.hardware.audio.output,android.software.backup,android.software.webview,android.hardware.opengles.aep,android.hardware.vulkan.version
Platforms=arm64-v8a,armeabi-v7a
Locales=en_US,ko_KR,zh_CN,zh_TW,ja_JP
