Build.BRAND=google
Build.DEVICE=cheetah
Build.MODEL=Pixel 7 Pro
Build.MANUFACTURER=Google
Build.PRODUCT=cheetah
Build.HARDWARE=cheetah
Build.ID=AP1A.240405.002
Build.FINGERPRINT=google/cheetah/cheetah:14/AP1A.240405.002/11649233:user/release-keys
Build.VERSION.SDK_INT=34
Build.VERSION.RELEASE=14
Screen.Density=560
Screen.Width=1440
Screen.Height=3120
Vending.versionString=41.3.22-29 [0] [PR] 640887647
Vending.version=84132210
Build.RADIO=g5300n-230203-230323-B-9801058,g5300n-230203-230323-B-9801058
Build.BOOTLOADER=cheetah-1.0-9716681
Client=android-google
GSF.version=203615037
CellOperator=310
SimOperator=310
Roaming=mobile-notroaming
TimeZone=UTC-10
TouchScreen=3
Keyboard=1
Navigation=1
ScreenLayout=2
HasHardKeyboard=false
HasFiveWayNavigation=false
LowRamDevice=false
MaxNumOfCPUCores=8
TotalMemoryBytes=8354971648
GL.Version=196608
GL.Extensions=GL_OES_egl_image_external,GL_OES_texture_npot,GL_KHR_texture_compression_astc_ldr
SharedLibraries=android.test.base,com.google.android.gms,android.ext.shared
Features=android.hardware.location,android.hardware.location.gps,android.hardware.location.network,android.hardware.wifi,android.hardware.wifi.direct,android.hardware.bluetooth,android.hardware.bluetooth_le,android.hardware.touchscreen,android.hardware.touchscreen.multitouch,android.hardware.touchscreen.multitouch.jazzhand,android.hardware.screen.portrait,android.hardware.screen.landscape,android.hardware.camera,android.hardware.camera.front,android.hardware.camera.flash,android.hardware.camera.autofocus,android.hardware.sensor.accelerometer,android.hardware.sensor.gyroscope,android.hardware.sensor.compass,android.hardware.sensor.proximity,android.hardware.sensor.light,android.hardware.telephony,android.hardware.telephony.gsm,android.hardware.nfc,android.hardware.nfc.hce,android.hardware.usb.host,android.hardware.usb.accessory,android.hardware.microphone,android.hardware.audio.output,android.hardware.audio.low_latency,android.hardware.fingerprint,android.hardware.opengles.aep,android.software.backup,android.software.print,android.software.input_methods,android.software.managed_users,android.software.app_widgets,android.hardware.vulkan.version,android.software.webview
Platforms=arm64-v8a
Locales=en_US,en_GB,en_IN,id_ID,ms_MY,zh_CN,zh_TW,hi_IN,ja_JP,ko_KR,th_TH,vi_VN,ar_EG,pt_BR,es_ES,es_US,fr_FR,de_DE,it_IT,ru_RU,tr_TR,pl_PL,nl_NL,sv_SE,da_DK,fi_FI
